<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Halo.Widgets</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\assets\halo.ico</ApplicationIcon>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TieredPgo>true</TieredPgo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Halo.Shared\Halo.Shared.csproj" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
    <PackageReference Include="Vortice.DirectComposition" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
  </ItemGroup>
</Project>
